### ISSUE TITLE
Use of React Typescript instead of static HTML?

### ISSUE THREAD

**Issue by BenNeighbour** [matbroughty/timstwitterlisteningparty#16]
👋 Hi @matbroughty @gingerbeardman @johnruane @ajbrindle, I'm looking to be an active contributor to this project in some way shape or form! I really like the website and would be super interested to help with developing new features or performing bug fixes.

I'd highly recommend the use of React with Typescript for this project (even though I realize this has already been done in vanilla HTML or whatever you are currently using) - I'd be more than happy to convert all of this into a React project if this gets the okay? I just think that in order for the platform to grow even more + be more maintainable for other contributors it would be a good idea to use React - as React Components are more modular and easier to read/develop/get others on-board. This also ensures more security (from object pollution, input sanitation, injections, etc...). Then you could just plug in a CDN/CMS to make it easier to put new albums on there for different dates. 

Again, I'm not too sure what libraries are being used for the UI here - if if anybody could outline the tech-stack that would be much appreciated. 👍

Also, is there any functionality where everyone can log into the site and listen in-sync with everybody else rather than just scheduling a time? Would be happy to design/work on a feature like that as I think it will make this platform even better. Point me to any ongoing Issues/PRs and I'd be happy to try and help out with those too.

Many thanks, Ben Neighbour

**Comment by matbroughty** [comment]
Morning @BenNeighbour 

Thanks for contacting us! 

Due to budget constraints (none!) the site is done as [static html via AWS S3 buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html) (largely using [bootstrap](https://getbootstrap.com)) so we are constrained a bit/lot to that to keep costs down.  We do now use WordPress for the shop.timstwitterlisteningparty.com but the main site runs off of static html in S3, so React probably going to be tricky to squeeze into what we do for now. When static HTML code is delivered to GitHub that triggers AWS CodeDeploy which moves it all over to the S3 buckets and it is live.

Then for the main part of the site we have some data files in csv (i.e. http://timstwitterlisteningparty.com/data/time-slot-data.csv for all the listening parties past and future) and I have written some AWS Lambda's (in Kotlin - see com.timstwitterlisteningparty.tools.lambda) that pick up any changes to the csv file and via [Freemarker](https://freemarker.apache.org) regenerate the html pages and the Lambda writes the updated html files back to the s3 buckets so they are available on internet.  Some jiggery pokery also happens with [AWS CloudFront ](https://aws.amazon.com/cloudfront/)so that all the pages are refreshed and available to the world.

The replay part of the site is handled by @ajbrindle and he has his own set of libraries that generate the html that you can see in GitHub for the replay pages - so that generation of the static pages (pages/replay and snippets/replay) is done outside this code base but the resulting html is included in this code base so that when delivered to this GitHub repo it gets copied automatically to s3 - and so is live.

I use the https://github.com/redouane59/twittered library to put all the tweets from each listening party and put them in [Twitter Collections](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/curate-a-collection/api-reference/get-collections-entries) and then store them in the [data csv](http://timstwitterlisteningparty.com/data/time-slot-data.csv) file in column 7.  I added a couple of the [collections endpoints](https://github.com/redouane59/twittered/pull/114) into the [twittered]( https://github.com/redouane59/twittered) library but didn't get around to adding the remaining endpoints so that could be something to look into as was planning on doing more with the collections at some point.

Make any sense?
 
Mat

**Comment by BenNeighbour** [comment]
@matbroughty Yeah - that makes total sense just saw the GitHub actions you guys have set up and now I understand what's going on! Just seen the new test website - the design look pretty cool - a lot better than the current one. Had a look at the Kotlin code and saw you were using AWS as well - that's pretty nice! So is the Twitter account a Twitter Bot then - or are you manually tweeting about the events?

**Comment by BenNeighbour** [comment]
I'll close the discussion I created - didn't realize you were on a budget!

**Comment by BenNeighbour** [comment]
@matbroughty Are you using bootstrap 5?

**Comment by BenNeighbour** [comment]
@matbroughty But I was thinking that you could just develop in react and then have a GitHub Action to build it then copy to the S3 instance, and once it gets build it's already in vanilla HTML/CSS/JS anyways?

**Comment by BenNeighbour** [comment]
Are there any Issues that I can deal with at the moment? If not just add me to any issues in the future and I'll be happy to help out 👍

**Comment by matbroughty** [comment]
Hello @BenNeighbour 
Thanks.  I think for now as it is a relatively simple static site we will leave it as is.   I'm planning to start a separate project to get all the tweets from all the collections and persist them into a separate DB for archiving and searching/analytics purposes and that maybe a better candidate for a dynamic React UI.  Will let you know when I get started!
Thanks again.
Mat!

**Comment by BenNeighbour** [comment]
Okay that's understandable! I'll be happy to help with any Full-Stack projects you are open sourcing in the future. Good luck with this, it's a great platform! Cheers, Ben
